# Generated by Django 4.2.6 on 2023-10-24 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_comunicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('S', 'Suspensión de actividad'), ('C', 'Suspensión de clase'), ('I', 'Información')], max_length=1),
        ),
        migrations.CreateModel(
            name='EntidadAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades_administradas', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.entidad')),
            ],
        ),
    ]
