# Generated by Django 4.2.6 on 2023-10-24 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_comunicado_tipo_entidadadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidades_administradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entidadadmin',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
