# Generated by Django 4.2.6 on 2023-10-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_entidad_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='administrador',
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('S', 'Suspension de actividad'), ('C', 'Suspension de clase'), ('I', 'Informacion')], max_length=1),
        ),
        migrations.DeleteModel(
            name='EntidadAdmin',
        ),
    ]
